# Generated by Django 5.2.17 on 2026-09-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('property_type', models.CharField(choices=[('OPEN_PLOT', 'Open Plot'), ('VILLA', 'Villa'), ('APARTMENT', 'Apartment'), ('COMMERCIAL', 'Commercial Space'), ('OTHER', 'Other')], default='OPEN_PLOT', max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('location_description', models.TextField(blank=True)),
                ('total_area', models.CharField(blank=True, max_length=100)),
                ('total_plots', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('highlights', models.TextField(blank=True)),
                ('amenities', models.TextField(blank=True)),
                ('google_maps_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
