# Generated by Django 5.2.17 on 2026-09-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='amenities',
        ),
        migrations.AddField(
            model_name='project',
            name='brochure',
            field=models.FileField(blank=True, null=True, upload_to='projects/brochures/'),
        ),
        migrations.AddField(
            model_name='project',
            name='developer_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='layout_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/layouts/'),
        ),
        migrations.AddField(
            model_name='project',
            name='layout_pdf',
            field=models.FileField(blank=True, null=True, upload_to='projects/layouts/'),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='promoter_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
