# Generated by Django 5.2.17 on 2026-09-09 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_amenity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_type', models.CharField(max_length=200)),
                ('approval_number', models.CharField(blank=True, max_length=200)),
                ('authority', models.CharField(blank=True, max_length=200)),
                ('document', models.FileField(blank=True, null=True, upload_to='projects/approvals/')),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='core.project')),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
