# Generated by Django 5.2.17 on 2026-09-09 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_projectapproval'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_number', models.CharField(max_length=50)),
                ('plot_size', models.CharField(blank=True, max_length=100)),
                ('dimension', models.CharField(blank=True, max_length=100)),
                ('facing', models.CharField(blank=True, max_length=50)),
                ('block', models.CharField(blank=True, max_length=50)),
                ('layout_position', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='core.project')),
            ],
            options={
                'ordering': ['plot_number'],
            },
        ),
    ]
