# Generated by Django 5.2.17 on 2026-09-09 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_plot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('message', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('WEBSITE', 'Website'), ('WHATSAPP', 'WhatsApp'), ('INSTAGRAM', 'Instagram'), ('FACEBOOK', 'Facebook'), ('YOUTUBE', 'YouTube'), ('GOOGLE', 'Google'), ('PHONE', 'Phone'), ('OTHER', 'Other')], default='WEBSITE', max_length=20)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('INTERESTED', 'Interested'), ('SITE_VISIT_SCHEDULED', 'Site Visit Scheduled'), ('SITE_VISIT_DONE', 'Site Visit Done'), ('BOOKING_REQUESTED', 'Booking Requested'), ('BOOKED', 'Booked'), ('CLOSED', 'Closed'), ('NOT_INTERESTED', 'Not Interested')], default='NEW', max_length=30)),
                ('whatsapp_opt_in', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interested_plot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='core.plot')),
                ('interested_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='core.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
