# Generated by Django 5.2.17 on 2026-09-09 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sitevisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('CONTACTED', 'Contacted'), ('UNDER_PROCESS', 'Under Process'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to='core.lead')),
                ('plot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_requests', to='core.plot')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to='core.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
