# Generated by Django 5.2.17 on 2026-09-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_leadfollowup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('message_template', models.TextField()),
                ('campaign_type', models.CharField(choices=[('NEW_PROJECT', 'New Project Launch'), ('PROJECT_UPDATE', 'Project Update'), ('SITE_VISIT', 'Site Visit Invite'), ('VIDEO_UPDATE', 'New Video'), ('OFFER', 'Offer'), ('FOLLOW_UP', 'Follow-up'), ('OTHER', 'Other')], default='PROJECT_UPDATE', max_length=30)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
