# Generated by Django 5.2.17 on 2026-09-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_campaignrecipient'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(fields=('phone', 'interested_project'), name='unique_lead_phone_project'),
        ),
    ]
