# Generated by Django 5.2.17 on 2026-10-03 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_lead_unique_lead_phone_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='interested_plot',
        ),
        migrations.RemoveField(
            model_name='bookingrequest',
            name='plot',
        ),
        migrations.DeleteModel(
            name='Plot',
        ),
    ]
